export const inputWrapper: string;
export const addon: string;
export const input: string;
export const small: string;
export const medium: string;
export const large: string;
export const full: string;
export const withAddons: string;
export const errorInput: string;
