export const form: string;
export const formGroup: string;
export const start: string;
export const center: string;
export const alignStart: string;
export const alignCenter: string;
export const formField: string;
export const formFieldError: string;
export const error: string;
